"""create initial domain tables

Revision ID: bbcbc813983d
Revises: 54de919c889c
Create Date: 2026-03-25 22:02:05.311708

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bbcbc813983d"
down_revision: Union[str, Sequence[str], None] = "54de919c889c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
